version: "3.9"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    networks:
      - poke-net
    depends_on:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    build: ./backend
    container_name: backend
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"
    networks:
      - poke-net
    depends_on:
      - db
      - rabbitmq
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/pokeguesser
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASS: password
    volumes:
      - ./backend:/app
      
  frontend:
    build: ./frontend
    container_name: frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    depends_on:
      - backend
    networks:
      - poke-net


  worker:
    image: python:3.11-slim
    container_name: worker
    volumes:
      - ./backend:/app
    working_dir: /app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/pokeguesser
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASS: password
      EMBEDDING_MODEL: all-MiniLM-L6-v2
    depends_on:
      - db
      - rabbitmq
    networks:
      - poke-net
    command: bash -c "pip install --no-cache-dir -r requirements.txt && while [ ! -f /app/consumer/consumer_math.py ]; do echo 'esperando archivos mapeados...'; sleep 1; done; python consumer/consumer_math.py"

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pokeguesser
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./backend/db/data:/var/lib/postgresql/data
    networks:
      - poke-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_pokeguesser
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "15672:15672"   # dashboard
    networks:
      - poke-net

networks:
  poke-net:
    driver: bridge
